COMPONENT=DataAggregationAppC
SENSORBOARD=mda100
CFLAGS += -I/opt/tinyos-2.1.1/tos/lib/net \
          -I/opt/tinyos-2.1.1/tos/lib/net/le \
          -I/opt/tinyos-2.1.1/tos/lib/net/ctp \
          -I/opt/tinyos-2.1.1/tos/sensorboards/mda100/cb
	
include $(MAKERULES)
